FROM gradle:8.5.0-jdk17

WORKDIR /app

COPY . /app
USER root
RUN chown -R gradle /app
USER gradle

RUN chmod +x ./gradlew
RUN ./gradlew clean build

COPY src ./src

EXPOSE 8080

CMD ["java", "-jar", "build/libs/fiap-fastfood-order-0.0.1-SNAPSHOT.jar"]